version: '3.7'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: cosc304-java
        depends_on:
            - db
        container_name: cosc304-java-Project
        volumes:
            - ./WebContent:/usr/local/tomcat/webapps/shop/
        networks:
            shop-network:
                aliases:
                    - cosc304-java
        ports:
            - 80:8080
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql-304Project
        restart: always
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: 'YourStrong@Passw0rd'
        ports:
            - '1434:1434'
        expose:
            - '1434'
        volumes:
            - cosc304-db:/var/lib/mssql
        networks:
            shop-network:
                aliases:
                    - cosc304-db
volumes: 
    cosc304-db:
networks:
    shop-network: